### ISSUE TITLE
community page

### ISSUE THREAD

**Issue by apoorvasrinivasan** [pydelhi/pydelhi_mobile#38]
- No image
- text has "/n"
- the footer duplicates on page load. 

![photo_2017-03-14_22-44-47](https://cloud.githubusercontent.com/assets/11849763/23913125/fa1db9bc-0907-11e7-96f4-fc61a1dbfc6d.jpg)

**Comment by shivan1b** [comment]
Fixed by commit 042d4ca50910c8a3e7616d6b020288abb3ba4251.
